# Use Python 3.8
FROM python:3.8-slim AS compile-image
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Install dependencies
RUN apt update && apt install -y \
      g++-11 \
      zlib1g-dev \
      build-essential \
      htop \
      vim \
      nano \
      tmux \
      git \
      rsync \
      wget

# Install SCENIC+
# Bravo Gonzalez-Blas, C. & De Winter, S. et al. (2022).
# SCENIC+: single-cell multiomic inference of enhancers and gene regulatory networks
RUN git clone https://github.com/aertslab/scenicplus && \
    cd scenicplus && \
    pip install -e .

# Install Jupyter Notebook
RUN pip install notebook
