# Use Python 3.11
FROM python:3.11

# Install dependencies
RUN apt update && apt install -y \
      g++-11 \
      zlib1g-dev \
      build-essential \
      htop \
      vim \
      nano \
      tmux \
      git \
      rsync \
      wget

# Install SCENIC+ & Jupyter Notebook
RUN pip3 install git+https://github.com/aertslab/scenicplus@development && \
    pip3 install jupyterlab && \
    pip3 install notebook
