# Use Conda rather than Python
FROM continuumio/miniconda3

# Install software
RUN apt-get update && \
    apt-get install -y \
      software-properties-common \
      g++-11 \
      zlib1g-dev \
      libcurl4-openssl-dev \
      zlib1g-dev \
      libfftw3-dev \
      libc++-dev \
      hdf5-tools \
      python3-launchpadlib \
      build-essential \
      procps \
      less \
      htop \
      vim \
      nano \
      tmux \
      git \
      rsync \
      wget

# Clone repo and create Conda environment
RUN git clone https://github.com/aertslab/create_cisTarget_databases && \
    cd create_cisTarget_databases \
    conda create -y -n create_cistarget_databases && \
    conda install -y \
      "python=3.10" \
      "numpy=1.21" \
      "pandas>=1.4.1" \
      "pyarrow>=7.0.0" \
      "numba>=0.55.1" \
      "python-flatbuffers"

# Install Cluster-Buster
# RUN echo "source activate create_cistarget_databases" > ~/.bashrc
# ENV PATH /opt/conda/envs/create_cistarget_databases/bin:$PATH
# RUN conda activate create_cistarget_databases
SHELL ["conda", "run", "-n", "create_cistarget_databases", "/bin/bash", "-c"]
RUN cd "${CONDA_PREFIX}/bin" && \
    wget https://resources.aertslab.org/cistarget/programs/cbust
